---
substitutions:
  name: garage-door-andy-ratgdo
  friendly_name: Garage Door - Andy
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25board_esp8266_d1_mini_lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret garage_door_andy_ratgdo_api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  domain: .greyrock.io
