---
substitutions:
  system_name: garage-door-andy-ratgdo
  host_name: garage-door-andy-ratgdo.greyrock.io
  friendly_name: Garage Door - Andy
  device_description: Ratgdo 2.5 board for Andy's Garage Door

packages:
  device: !include devices/v25board_esp8266_d1_mini_lite.yaml
