substitutions:
  device_name: "light-office-ceiling-1"
  friendly_name: "light-office-ceiling-1"
  project_name: "Athom Technology.RGBCW Bulb"
  project_version: "1.1"
  light_restore_mode: RESTORE_AND_OFF
  color_interlock: 'true'

packages:
  device: !include devices/athom-gu10.yaml
