---
# Time
#
# The time component allows you to set up real time clock time sources
# for ESPHome.
#
# https://esphome.io/components/time.html
#
substitutions:
  time_timezone: "America/New_York"

time:
  - <<: !include ../time/sntp.yaml
    timezone: "${time_timezone}"
    servers:
      - time1.greyrock.io
      - time2.greyrock.io
      - time3.greyrock.io
