---
name: Schedule - Keepalive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/scheduled-keepalive.yaml"

jobs:
  keepalive:
    name: Keep scheduled GitHub workflows alive
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub API token
        id: get-app-token
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: ${{ secrets.GREYROCK_APP_ID }}
          private_key: ${{ secrets.GREYROCK_APP_PRIVATE_KEY }}

      - name: Checkout main branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ steps.get-app-token.outputs.token }}

      - name: Keep scheduled GitHub workflows alive
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          gh_token: ${{ steps.get-app-token.outputs.token }}
          committer_username: "greyrock-repo-duster[bot]"
          committer_email: "greyrock-repo-duster <112729691+greyrock-repo-duster[bot]@users.noreply.github.com>"
